server:
  port: 9999
  
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/log?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
    username: root
    password: root
    
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl